# Project-wide Gradle settings.

# Increase JVM heap size to prevent OutOfMemoryError during R8 minification and Gradle build
org.gradle.jvmargs=-Xmx4096m -XX:+UseG1GC -XX:MaxMetaspaceSize=1024m

# AndroidX support
android.useAndroidX=true

# Speed up build with parallel execution & caching
org.gradle.parallel=true
org.gradle.caching=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
